language: node_js
node_js:
  - lts/*
os:
  - linux
  - windows
  - osx
before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt update;
      sudo apt install snapd;
      sudo snap install snapcraft --classic;
    fi
script:
  - npm run release