language: node_js
node_js:
  - lts/*
os:
  - linux
  - windows
  - osx
env:
  - GH_TOKEN=b56fbc4a2a14ab92905e1fffec0889d4e4e0e68b
before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt update;
      sudo apt install snapd;
      sudo snap install snapcraft --classic;
    fi
script:
  - npm run release